# Generated by Django 4.0.3 on 2022-12-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_classroom_student_classroom_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
